@startuml


title Cancel_itm \n**Design** Sequence Diagram\n

actor Server as client
participant ":view : ServerView" as svv
participant "controller: OrderController" as odc
participant "tc: TableController" as tc
participant "order: Order" as or
participant "items: \n List[OrderItem]" as it

activate client


client -> svv ++: [ red X button associated to an order]
svv->odc++: cancel_item(menu_item)
odc->or++:cancel_item(menu_item)
or->or: unordored = unordored_items()


loop item : OrderItem in odc:
    activate it
    or->it:mark_as_ordered()

    end


odc-->tc**: (view, restaurant, table)
deactivate it
activate svv
odc->svv--: set_controller(tc)

svv->tc++:create_ui()


tc->svv--:create_table_ui(table)
activate svv
deactivate svv





deactivate



deactivate



@enduml